
-- Membuang struktur basisdata untuk informasi
USE `informasi`;

-- membuang struktur untuk procedure informasi.executeJumlahTempatTidur
DROP PROCEDURE IF EXISTS `executeJumlahTempatTidur`;
DELIMITER //
CREATE PROCEDURE `executeJumlahTempatTidur`()
BEGIN
		
	BEGIN		
		DECLARE VTANGGAL DATE;
		DECLARE VRUANGAN_ID CHAR(10);
		DECLARE VJUMLAH SMALLINT;
		DECLARE V_VVIP SMALLINT;
		DECLARE V_VIP SMALLINT;
		DECLARE VKELAS_1 SMALLINT;
		DECLARE VKELAS_2 SMALLINT;
		DECLARE VKELAS_3 SMALLINT;
		DECLARE VISOLASI SMALLINT;
		DECLARE VINTENSIF SMALLINT;
		DECLARE VHCU SMALLINT;
		DECLARE VNON_KELAS SMALLINT;
		DECLARE VLASTUPDATED DATETIME;
		
		DECLARE EXEC_NOT_FOUND TINYINT DEFAULT FALSE;		
		DECLARE CR_EXEC CURSOR FOR SELECT DATE(NOW()) TANGGAL,  r.ID RUANGAN_ID, COUNT(*) JUMLAH
						, SUM(IF(gk.KELAS=5,1,0)) VVIP
						, SUM(IF(gk.KELAS=4,1,0)) VIP
						, SUM(IF(gk.KELAS=3,1,0)) KELAS_1
						, SUM(IF(gk.KELAS=2,1,0)) KELAS_2
						, SUM(IF(gk.KELAS=1,1,0)) KELAS_3
						, SUM(IF(gk.KELAS=0 AND INSTR(kls.DESKRIPSI,'Isolasi') > 0,1,0)) ISOLASI
						, SUM(IF(gk.KELAS=0 AND INSTR(kls.DESKRIPSI,'Intensif') > 0,1,0)) INTENSIF
						, SUM(IF(gk.KELAS=0 AND INSTR(kls.DESKRIPSI,'HCU') > 0,1,0)) HCU
						, SUM(IF(gk.KELAS=0 AND INSTR(kls.DESKRIPSI,'Non Kelas') > 0,1,0)) NON_KELAS
						, NOW() LASTUPDATED
				FROM `master`.ruangan r
					INNER JOIN `master`.ruang_kamar rk ON r.ID = rk.RUANGAN
					  LEFT JOIN `master`.referensi kls ON rk.KELAS = kls.ID AND kls.JENIS = 19
					  LEFT JOIN `master`.group_referensi_kelas gk ON kls.ID = gk.REFERENSI_KELAS
					  LEFT JOIN `master`.referensi rkls ON rkls.ID = gk.KELAS AND rkls.JENIS = 19
					INNER JOIN `master`.ruang_kamar_tidur rkt ON rk.ID = rkt.RUANG_KAMAR
					WHERE r.`STATUS` != 0 AND rk.`STATUS` != 0
					AND rkt.`STATUS` != 0 AND r.JENIS_KUNJUNGAN = 3
					AND INSTR(r.DESKRIPSI, 'IRNA') = 0
					GROUP BY r.ID;
			
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET EXEC_NOT_FOUND = TRUE;
						
		OPEN CR_EXEC;
						
		EXIT_EXEC: LOOP
			FETCH CR_EXEC INTO VTANGGAL, VRUANGAN_ID, VJUMLAH, V_VVIP, V_VIP, VKELAS_1, VKELAS_2, VKELAS_3, VISOLASI, VINTENSIF, VHCU, VNON_KELAS, VLASTUPDATED;
							
			IF EXEC_NOT_FOUND THEN
				LEAVE EXIT_EXEC;
			END IF;
			
			IF EXISTS(SELECT 1 
					FROM informasi.tempat_tidur 
				  WHERE TANGGAL = VTANGGAL 
				    AND RUANGAN_ID = VRUANGAN_ID) THEN
				UPDATE informasi.tempat_tidur
				   SET JUMLAH = VJUMLAH, VVIP = V_VVIP, VIP = V_VIP, KELAS_1 = VKELAS_1, KELAS_2 = VKELAS_2, KELAS_3 = VKELAS_3, ISOLASI = VISOLASI, INTENSIF = VINTENSIF, HCU = VHCU, NON_KELAS = VNON_KELAS, LASTUPDATED = VLASTUPDATED
				  WHERE TANGGAL = VTANGGAL 
				    AND RUANGAN_ID = VRUANGAN_ID;
			ELSE
				INSERT INTO informasi.tempat_tidur(TANGGAL, RUANGAN_ID, JUMLAH, VVIP, VIP, KELAS_1, KELAS_2, KELAS_3, ISOLASI, INTENSIF, HCU, NON_KELAS, LASTUPDATED)
					  VALUES (VTANGGAL, VRUANGAN_ID, VJUMLAH, V_VVIP, V_VIP, VKELAS_1, VKELAS_2, VKELAS_3, VISOLASI, VINTENSIF, VHCU, VNON_KELAS, VLASTUPDATED);
			END IF;
		END LOOP;
		
		CLOSE CR_EXEC;
	END;		
END//
DELIMITER ;


