INSERT INTO `kemkes_ruangan` (`ID`, `DESKRIPSI`) VALUES ('0000', 'Umum');
INSERT INTO `kemkes_ruangan` (`ID`, `DESKRIPSI`) VALUES ('0001', 'Anak');
INSERT INTO `kemkes_ruangan` (`ID`, `DESKRIPSI`) VALUES ('0002', 'Anak (Luka Bakar)');
INSERT INTO `kemkes_ruangan` (`ID`, `DESKRIPSI`) VALUES ('0003', 'Penyakit Dalam');
INSERT INTO `kemkes_ruangan` (`ID`, `DESKRIPSI`) VALUES ('0004', 'Kebidanan');
INSERT INTO `kemkes_ruangan` (`ID`, `DESKRIPSI`) VALUES ('0005', 'Kandungan');
INSERT INTO `kemkes_ruangan` (`ID`, `DESKRIPSI`) VALUES ('0006', 'Bedah');
INSERT INTO `kemkes_ruangan` (`ID`, `DESKRIPSI`) VALUES ('0007', 'Kanker');
INSERT INTO `kemkes_ruangan` (`ID`, `DESKRIPSI`) VALUES ('0008', 'Mata');
INSERT INTO `kemkes_ruangan` (`ID`, `DESKRIPSI`) VALUES ('0009', 'THT');
INSERT INTO `kemkes_ruangan` (`ID`, `DESKRIPSI`) VALUES ('0010', 'Paru');
INSERT INTO `kemkes_ruangan` (`ID`, `DESKRIPSI`) VALUES ('0011', 'Jantung');
INSERT INTO `kemkes_ruangan` (`ID`, `DESKRIPSI`) VALUES ('0012', 'Orthopedi');
INSERT INTO `kemkes_ruangan` (`ID`, `DESKRIPSI`) VALUES ('0013', 'Kulit dan Kelamin');
INSERT INTO `kemkes_ruangan` (`ID`, `DESKRIPSI`) VALUES ('0014', 'Saraf');
INSERT INTO `kemkes_ruangan` (`ID`, `DESKRIPSI`) VALUES ('0015', 'Jiwa');
INSERT INTO `kemkes_ruangan` (`ID`, `DESKRIPSI`) VALUES ('0016', 'Infeksi');
INSERT INTO `kemkes_ruangan` (`ID`, `DESKRIPSI`) VALUES ('0017', 'Luka Bakar');
INSERT INTO `kemkes_ruangan` (`ID`, `DESKRIPSI`) VALUES ('0018', 'NAPZA');
INSERT INTO `kemkes_ruangan` (`ID`, `DESKRIPSI`) VALUES ('0019', 'Isolasi Air Borne');
INSERT INTO `kemkes_ruangan` (`ID`, `DESKRIPSI`) VALUES ('0020', 'Isolasi TB MDR');
INSERT INTO `kemkes_ruangan` (`ID`, `DESKRIPSI`) VALUES ('0021', 'Kulit dan Kelamin');
INSERT INTO `kemkes_ruangan` (`ID`, `DESKRIPSI`) VALUES ('0022', 'Isolasi Imunitas men');
INSERT INTO `kemkes_ruangan` (`ID`, `DESKRIPSI`) VALUES ('0023', 'Isolasi Radioaktif');
INSERT INTO `kemkes_ruangan` (`ID`, `DESKRIPSI`) VALUES ('0024', 'ICU');
INSERT INTO `kemkes_ruangan` (`ID`, `DESKRIPSI`) VALUES ('0025', 'NICU');
INSERT INTO `kemkes_ruangan` (`ID`, `DESKRIPSI`) VALUES ('0026', 'PICU');
INSERT INTO `kemkes_ruangan` (`ID`, `DESKRIPSI`) VALUES ('0027', 'CVCU/ICCU');
INSERT INTO `kemkes_ruangan` (`ID`, `DESKRIPSI`) VALUES ('0028', 'RICU');
INSERT INTO `kemkes_ruangan` (`ID`, `DESKRIPSI`) VALUES ('0029', 'HCU');
INSERT INTO `kemkes_ruangan` (`ID`, `DESKRIPSI`) VALUES ('0030', 'Kedokteran Nuklir');
