CREATE TABLE `tempat_tidur` (
	`TANGGAL` DATE NOT NULL,
	`RUANGAN_ID` CHAR(50) NOT NULL COLLATE 'latin1_swedish_ci',
	`JUMLAH` SMALLINT(6) NULL DEFAULT NULL,
	`VVIP` SMALLINT(6) NULL DEFAULT NULL,
	`VIP` SMALLINT(6) NULL DEFAULT NULL,
	`KELAS_1` SMALLINT(6) NULL DEFAULT NULL,
	`KELAS_2` SMALLINT(6) NULL DEFAULT NULL,
	`KELAS_3` SMALLINT(6) NULL DEFAULT NULL,
	`ISOLASI` SMALLINT(6) NULL DEFAULT NULL,
	`INTENSIF` SMALLINT(6) NULL DEFAULT NULL,
	`HCU` SMALLINT(6) NULL DEFAULT NULL,
	`NON_KELAS` SMALLINT(6) NULL DEFAULT NULL,
	`LASTUPDATED` DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (`TANGGAL`, `RUANGAN_ID`) USING BTREE,
	INDEX `LASTUPDATED` (`LASTUPDATED`) USING BTREE
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;
